import habitat_sim
import magnum as mn
from _typeshed import Incomplete
from typing import List

class SpotAgent:
    SPOT_DIR: str
    class ExtractedBaseVelNonCylinderAction:
        spot: Incomplete
        base_vel_ctrl: Incomplete
        def __init__(self, sim, spot) -> None: ...
        def collision_check(self, trans, target_trans, target_rigid_state, compute_sliding): ...
        def update_base(self, if_rotation) -> None: ...
        def toggle_clip(self, largest_island_ix: int): ...
        def step(self, forward, lateral, angular) -> None: ...
    sim: Incomplete
    largest_island_ix: int
    spot_forward: float
    spot_lateral: float
    spot_angular: float
    camera_angles: Incomplete
    spot_rigid_state: Incomplete
    spot_motion_type: Incomplete
    def __init__(self, sim: habitat_sim.Simulator) -> None: ...
    spot: Incomplete
    spot_action: Incomplete
    def load_and_init(self) -> None: ...
    camera_distance: float
    lookat_height: float
    def init_spot_cam(self) -> None: ...
    def mod_spot_cam(self, scroll_mod_val: float = 0, mse_rel_pos: List = None, shift_pressed: bool = False, alt_pressed: bool = False): ...
    def set_agent_camera_transform(self, agent_node) -> None: ...
    def base_pos(self): ...
    def place_on_navmesh(self) -> None: ...
    def toggle_clip(self) -> None: ...
    def move_spot(self, move_fwd: bool, move_back: bool, move_up: bool, move_down: bool, slide_left: bool, slide_right: bool, turn_left: bool, turn_right: bool): ...
    def cache_transform_and_remove(self) -> None: ...
    def restore_at_previous_loc(self) -> None: ...
    def get_point_in_front(self, disp_in_front: mn.Vector3 = None): ...
