def run_command(command: str) -> str: ...
def get_gcc_version() -> str: ...
def get_cmake_version() -> str: ...
def get_nvidia_smi() -> str: ...
def get_pip_packages() -> str: ...
def get_conda_packages() -> str: ...
def main() -> None: ...
