import magnum as mn
import numpy as np
import quaternion as qt
from habitat_sim._ext.habitat_sim_bindings.core import orthonormalize_rotation_shear as orthonormalize_rotation_shear
from typing import List, Sequence, Tuple

def quat_from_coeffs(coeffs: Sequence[float] | np.ndarray) -> qt.quaternion: ...
def quat_to_coeffs(quat: qt.quaternion) -> np.ndarray: ...
def quat_to_magnum(quat: qt.quaternion) -> mn.Quaternion: ...
def quat_from_magnum(quat: mn.Quaternion) -> qt.quaternion: ...
def quat_to_angle_axis(quat: qt.quaternion) -> Tuple[float, np.ndarray]: ...
def quat_from_angle_axis(theta: float, axis: np.ndarray) -> qt.quaternion: ...
def quat_from_two_vectors(v0: np.ndarray, v1: np.ndarray) -> qt.quaternion: ...
def angle_between_quats(q1: qt.quaternion, q2: qt.quaternion) -> float: ...
def quat_rotate_vector(q: qt.quaternion, v: np.ndarray) -> np.ndarray: ...
def random_quaternion(): ...
def download_and_unzip(file_url, local_directory) -> None: ...
def colorize_ids(ids): ...

d3_40_colors_rgb: np.ndarray
d3_40_colors_hex: List[str]
