from contextlib import ContextDecorator
from habitat_sim.logging import logger as logger

class _ProfilingHelper:
    step_count: int
    capture_start_step: int
    capture_end_step: int
    range_depth: int

def configure(capture_start_step: int = -1, num_steps_to_capture: int = -1) -> None: ...
def on_start_step() -> None: ...
def range_push(msg: str) -> None: ...
def range_pop() -> None: ...

class RangeContext(ContextDecorator):
    def __init__(self, msg: str) -> None: ...
    def __enter__(self) -> RangeContext: ...
    def __exit__(self, *exc) -> None: ...
