import habitat_sim
import magnum as mn
from _typeshed import Incomplete
from habitat_sim.utils.namespace.hsim_physics import get_obj_from_handle as get_obj_from_handle, get_obj_from_id as get_obj_from_id
from typing import Any, Dict, Set

class MarkerSetsEditor:
    sim: Incomplete
    markerset_taskset_names: Incomplete
    def __init__(self, sim: habitat_sim.simulator.Simulator, task_names_set: Set = None) -> None: ...
    marker_sets_per_obj: Incomplete
    markerset_label_prefix: Incomplete
    current_markerset_taskset_idx: int
    marker_sets_changed: Incomplete
    marker_debug_random_colors: Incomplete
    glbl_marker_point_dicts_per_obj: Incomplete
    def update_markersets(self) -> None: ...
    def get_current_taskname(self): ...
    def cycle_current_taskname(self, forward: bool = True): ...
    def set_current_taskname(self, taskname: str): ...
    def get_all_markersets(self): ...
    def place_marker_at_hit_location(self, hit_info, ao_link_map: Dict[int, int], add_marker: bool): ...
    def draw_marker_sets_debug(self, debug_line_render: Any, camera_position: mn.Vector3) -> None: ...
    def save_all_dirty_markersets(self) -> None: ...
    def save_markerset_attributes(self, obj) -> None: ...
    def get_all_global_markers(self): ...
    def _draw_markersets_glbl_debug_objtype(self, obj_type_key: str, debug_line_render: Any, camera_position: mn.Vector3) -> None: ...
    def draw_markersets_glbl_debug(self, debug_line_render: Any, camera_position: mn.Vector3) -> None: ...
