import magnum as mn
import numpy as np
import quaternion as qt
from typing import Sequence, Tuple

def quat_from_coeffs(coeffs: Sequence[float] | np.ndarray) -> qt.quaternion: ...
def quat_to_coeffs(quat: qt.quaternion) -> np.ndarray: ...
def quat_to_magnum(quat: qt.quaternion) -> mn.Quaternion: ...
def quat_from_magnum(quat: mn.Quaternion) -> qt.quaternion: ...
def quat_to_angle_axis(quat: qt.quaternion) -> Tuple[float, np.ndarray]: ...
def quat_from_angle_axis(theta: float, axis: np.ndarray) -> qt.quaternion: ...
def quat_from_two_vectors(v0: np.ndarray, v1: np.ndarray) -> qt.quaternion: ...
def angle_between_quats(q1: mn.Quaternion, q2: mn.Quaternion) -> float: ...
def quat_rotate_vector(q: qt.quaternion, v: np.ndarray) -> np.ndarray: ...
def random_quaternion(): ...
