from _typeshed import Incomplete
from typing import Type

class _Registry:
    @classmethod
    def register_move_fn(cls, controller: Type | None = None, *, name: str | None = None, body_action: bool | None = None): ...
    @classmethod
    def register_noise_model(cls, noise_model: Type | None = None, *, name: str | None = None): ...
    @classmethod
    def register_pose_extractor(cls, pose_extractor: Type | None = None, *, name: str | None = None): ...
    @classmethod
    def get_move_fn(cls, name: str): ...
    @classmethod
    def get_noise_model(cls, name: str): ...
    @classmethod
    def get_pose_extractor(cls, name: str): ...

registry: Incomplete
