import habitat_sim
import magnum as mn
from habitat_sim import physics as HSim_Phys
from typing import Dict, List

def get_link_normalized_joint_position(object_a: HSim_Phys.ManagedArticulatedObject, link_ix: int) -> float: ...
def set_link_normalized_joint_position(object_a: HSim_Phys.ManagedArticulatedObject, link_ix: int, normalized_pos: float) -> None: ...
def link_is_open(object_a: HSim_Phys.ManagedArticulatedObject, link_ix: int, threshold: float = 0.4) -> bool: ...
def link_is_closed(object_a: HSim_Phys.ManagedArticulatedObject, link_ix: int, threshold: float = 0.1) -> bool: ...
def open_link(object_a: HSim_Phys.ManagedArticulatedObject, link_ix: int) -> None: ...
def close_link(object_a: HSim_Phys.ManagedArticulatedObject, link_ix: int) -> None: ...
def get_bb_corners(range3d: mn.Range3D) -> List[mn.Vector3]: ...
def get_ao_root_bb(ao: HSim_Phys.ManagedArticulatedObject) -> mn.Range3D: ...
def get_ao_default_link(ao: habitat_sim.physics.ManagedArticulatedObject, compute_if_not_found: bool = False) -> int | None: ...
def get_ao_link_id_map(sim: habitat_sim.Simulator) -> Dict[int, int]: ...
def get_global_keypoints_from_bb(aabb: mn.Range3D, local_to_global: mn.Matrix4) -> List[mn.Vector3]: ...
def get_articulated_link_global_keypoints(object_a: habitat_sim.physics.ManagedArticulatedObject, link_index: int) -> List[mn.Vector3]: ...
def get_obj_from_id(sim: habitat_sim.Simulator, obj_id: int, ao_link_map: Dict[int, int] | None = None) -> HSim_Phys.ManagedRigidObject | HSim_Phys.ManagedArticulatedObject: ...
def get_obj_from_handle(sim: habitat_sim.Simulator, obj_handle: str) -> HSim_Phys.ManagedRigidObject | HSim_Phys.ManagedArticulatedObject: ...
def get_all_ao_objects(sim: habitat_sim.Simulator) -> List[HSim_Phys.ManagedArticulatedObject]: ...
def get_all_rigid_objects(sim: habitat_sim.Simulator) -> List[HSim_Phys.ManagedArticulatedObject]: ...
def get_all_objects(sim: habitat_sim.Simulator) -> List[HSim_Phys.ManagedRigidObject | HSim_Phys.ManagedArticulatedObject]: ...
