from _typeshed import Incomplete
from abc import ABC, abstractmethod
from habitat_sim.physics import ManagedBulletArticulatedObject as ManagedBulletArticulatedObject

class RobotInterface(ABC):
    sim_obj: Incomplete
    def __init__(self) -> None: ...
    def get_robot_sim_id(self) -> int: ...
    @abstractmethod
    def update(self): ...
    @abstractmethod
    def reset(self): ...
    @abstractmethod
    def reconfigure(self): ...
    def get_link_and_joint_names(self) -> str: ...
