from habitat_sim.robots.mobile_manipulator import MobileManipulator as MobileManipulator, MobileManipulatorParams as MobileManipulatorParams, RobotCameraParams as RobotCameraParams

class FetchRobot(MobileManipulator):
    back_joint_id: int
    head_rot_jid: int
    head_tilt_jid: int
    def __init__(self, urdf_path, sim, limit_robo_joints: bool = True, fixed_base: bool = True) -> None: ...
    def reconfigure(self) -> None: ...
    def reset(self) -> None: ...
    @property
    def base_transformation(self): ...
    def update(self) -> None: ...

class FetchRobotNoWheels(FetchRobot):
    def __init__(self, urdf_path, sim, limit_robo_joints: bool = True, fixed_base: bool = True) -> None: ...
