import magnum as mn
import numpy as np
from _typeshed import Incomplete
from habitat_sim.physics import JointMotorSettings as JointMotorSettings
from habitat_sim.robots.robot_interface import RobotInterface as RobotInterface
from habitat_sim.simulator import Simulator as Simulator
from habitat_sim.utils.common import orthonormalize_rotation_shear as orthonormalize_rotation_shear
from typing import Dict, List, Set, Tuple

class RobotCameraParams:
    attached_link_id: int
    cam_offset_pos: mn.Vector3
    cam_look_at_pos: mn.Vector3
    relative_transform: mn.Matrix4

class MobileManipulatorParams:
    arm_joints: List[int]
    gripper_joints: List[int]
    wheel_joints: List[int] | None
    arm_init_params: np.ndarray | None
    gripper_init_params: np.ndarray | None
    ee_offset: mn.Vector3
    ee_link: int
    ee_constraint: np.ndarray
    cameras: Dict[str, RobotCameraParams]
    gripper_closed_state: np.ndarray
    gripper_open_state: np.ndarray
    gripper_state_eps: float
    arm_mtr_pos_gain: float
    arm_mtr_vel_gain: float
    arm_mtr_max_impulse: float
    wheel_mtr_pos_gain: float
    wheel_mtr_vel_gain: float
    wheel_mtr_max_impulse: float
    base_offset: mn.Vector3
    base_link_names: Set[str]

class MobileManipulator(RobotInterface):
    urdf_path: Incomplete
    params: Incomplete
    sim_obj: Incomplete
    joint_motors: Incomplete
    joint_pos_indices: Incomplete
    joint_dof_indices: Incomplete
    joint_limits: Incomplete
    def __init__(self, params: MobileManipulatorParams, urdf_path: str, sim: Simulator, limit_robo_joints: bool = True, fixed_base: bool = True) -> None: ...
    def reconfigure(self) -> None: ...
    def update(self) -> None: ...
    def reset(self) -> None: ...
    @property
    def arm_joint_limits(self) -> Tuple[np.ndarray, np.ndarray]: ...
    @property
    def ee_link_id(self) -> int: ...
    @property
    def ee_local_offset(self) -> mn.Vector3: ...
    def calculate_ee_forward_kinematics(self, joint_state: np.ndarray) -> np.ndarray: ...
    def calculate_ee_inverse_kinematics(self, ee_target_position: np.ndarray) -> np.ndarray: ...
    @property
    def ee_transform(self) -> mn.Matrix4: ...
    @property
    def gripper_joint_pos(self) -> np.ndarray: ...
    @gripper_joint_pos.setter
    def gripper_joint_pos(self, ctrl: List[float]): ...
    def set_gripper_target_state(self, gripper_state: float) -> None: ...
    def close_gripper(self) -> None: ...
    def open_gripper(self) -> None: ...
    @property
    def is_gripper_open(self) -> bool: ...
    @property
    def is_gripper_closed(self) -> bool: ...
    @property
    def arm_joint_pos(self) -> np.ndarray: ...
    @arm_joint_pos.setter
    def arm_joint_pos(self, ctrl: List[float]): ...
    def set_fixed_arm_joint_pos(self, fix_arm_joint_pos) -> None: ...
    @property
    def arm_velocity(self) -> np.ndarray: ...
    @property
    def arm_motor_pos(self) -> np.ndarray: ...
    @arm_motor_pos.setter
    def arm_motor_pos(self, ctrl: List[float]) -> None: ...
    def clip_ee_to_workspace(self, pos: np.ndarray) -> np.ndarray: ...
    @property
    def base_pos(self): ...
    @base_pos.setter
    def base_pos(self, position: mn.Vector3): ...
    @property
    def base_rot(self) -> float: ...
    @base_rot.setter
    def base_rot(self, rotation_y_rad: float): ...
    @property
    def base_transformation(self): ...
    def is_base_link(self, link_id: int) -> bool: ...
