import numpy as np
from PIL import Image
from _typeshed import Incomplete
from habitat_sim.utils.common import d3_40_colors_hex as d3_40_colors_hex, d3_40_colors_rgb as d3_40_colors_rgb
from typing import Any, Dict, List, Tuple

def is_notebook() -> bool: ...
def save_video(video_file: str, frames, fps: int = 60): ...
def display_video(video_file: str, height: int = 400): ...
def observation_to_image(observation_image: np.ndarray, observation_type: str, depth_clip: float | None = 10.0) -> Image.Image: ...
def border_frames_from_overlay(overlay_settings, observation_to_image=...): ...
def make_video_frame(ob, primary_obs: str, primary_obs_type: str, video_dims, overlay_settings: Incomplete | None = None, observation_to_image=...) -> Image.Image: ...
def make_video(observations: List[np.ndarray], primary_obs: str, primary_obs_type: str, video_file: str, fps: int = 60, open_vid: bool = True, video_dims: Tuple[int] | None = None, overlay_settings: List[Dict[str, Any]] | None = None, depth_clip: float | None = 10.0, observation_to_image=...): ...
def depth_to_rgb(depth_image: np.ndarray, clip_max: float = 10.0) -> np.ndarray: ...
def semantic_to_rgb(semantic_image: np.ndarray) -> Image.Image: ...
def get_island_colored_map(island_top_down_map_data: np.ndarray) -> Image.Image: ...
