import habitat_sim
import magnum as mn
from _typeshed import Incomplete
from enum import Enum
from habitat_sim.utils.namespace.hsim_physics import get_ao_root_bb as get_ao_root_bb, get_obj_from_handle as get_obj_from_handle, open_link as open_link
from typing import List

class ObjectEditor:
    class EditMode(Enum):
        MOVE: int
        ROTATE: int
        NUM_VALS: int
    EDIT_MODE_NAMES: Incomplete
    class DistanceMode(Enum):
        TINY: int
        VERY_SMALL: int
        SMALL: int
        MEDIUM: int
        LARGE: int
        HUGE: int
        NUM_VALS: int
    class ObjectTypeToDraw(Enum):
        NONE: int
        ARTICULATED: int
        RIGID: int
        BOTH: int
        NUM_VALS: int
    OBJECT_TYPE_NAMES: Incomplete
    DISTANCE_MODE_VALS: Incomplete
    ROTATION_MULT_VALS: Incomplete
    BASE_EDIT_ROT_AMT: Incomplete
    REMOVAL_DISP_VEC: Incomplete
    sim: Incomplete
    curr_edit_mode: Incomplete
    curr_edit_multiplier: Incomplete
    obj_type_to_draw: Incomplete
    def __init__(self, sim: habitat_sim.simulator.Simulator) -> None: ...
    def set_edit_mode_rotate(self) -> None: ...
    edit_translation_dist: Incomplete
    edit_rotation_amt: Incomplete
    def set_edit_vals(self) -> None: ...
    def get_target_sel_obj(self): ...
    def edit_disp_str(self): ...
    def edit_obj_disp_str(self): ...
    def set_sel_obj(self, obj) -> None: ...
    def toggle_sel_obj(self, obj) -> None: ...
    def sel_obj_list(self, obj_handle_list: List[str]): ...
    def set_ao_joint_states(self, do_open: bool, selected: bool, agent_name: str = 'hab_spot'): ...
    def move_sel_objects(self, navmesh_dirty: bool, translation: mn.Vector3 | None = None, rotation: mn.Quaternion | None = None, removal: bool = False) -> bool: ...
    def remove_sel_objects(self): ...
    def restore_removed_objects(self): ...
    def delete_removed_objs(self) -> None: ...
    def redo_sel_edits(self) -> None: ...
    def undo_sel_edits(self) -> None: ...
    def select_all_matching_objects(self, only_matches: bool): ...
    def match_dim_sel_objects(self, navmesh_dirty: bool, new_val: float, axis: mn.Vector3) -> bool: ...
    def match_x_dim(self, navmesh_dirty: bool) -> bool: ...
    def match_y_dim(self, navmesh_dirty: bool) -> bool: ...
    def match_z_dim(self, navmesh_dirty: bool) -> bool: ...
    def match_orientation(self, navmesh_dirty: bool) -> bool: ...
    def edit_left(self, navmesh_dirty: bool) -> bool: ...
    def edit_right(self, navmesh_dirty: bool): ...
    def edit_up(self, navmesh_dirty: bool, toggle: bool): ...
    def edit_down(self, navmesh_dirty: bool, toggle: bool): ...
    obj_last_save_transform: Incomplete
    modified_scene: bool
    def save_current_scene(self) -> None: ...
    def load_from_substring(self, navmesh_dirty: bool, obj_substring: str, build_loc: mn.Vector3): ...
    def build_objects(self, navmesh_dirty: bool, build_loc: mn.Vector3): ...
    def change_edit_mode(self, toggle: bool): ...
    def change_edit_vals(self, toggle: bool): ...
    def change_draw_box_types(self, toggle: bool): ...
    duplicate_rigid_object_cache: Incomplete
    duplicate_articulated_object_cache: Incomplete
    def handle_duplicate_objects(self, find_objs: bool, remove_dupes: bool, trans_eps: float = 0.1): ...
    def draw_obj_vis(self, camera_trans: mn.Vector3, debug_line_render): ...
    def draw_duplicate_objs(self, camera_trans: mn.Vector3, debug_line_render): ...
    def draw_selected_objects(self, debug_line_render) -> None: ...
    def draw_box_around_objs(self, debug_line_render, agent_name: str = 'hab_spot'): ...
