from argparse import ArgumentParser, Namespace
from sqlite3 import Connection
from typing import Any, DefaultDict, List

class Event:
    name: str
    thread_id: int
    start: int
    end: int

class SummaryItem:
    time_exclusive: int
    time_inclusive: int
    count: int

def get_sqlite_events(conn: Connection) -> List[Event]: ...
def create_summary_from_events(events: List[Event]) -> DefaultDict[str, SummaryItem]: ...
def _display_time_ms(time: int, args: Namespace, show_sign: bool = False) -> str: ...
def print_summaries(summaries: List[DefaultDict[str, SummaryItem]] | List[DefaultDict[Any, Any]], args: Namespace, labels: List[str] | None = None) -> None: ...
def get_sqlite_filepaths_from_directory(directory): ...
def create_arg_parser() -> ArgumentParser: ...
def main() -> None: ...
