from contextlib import ContextDecorator

class NoAttrValidationContext(ContextDecorator):
    original_state: bool | None
    def __enter__(self) -> NoAttrValidationContext: ...
    def __exit__(self, *exc) -> None: ...

def all_is_finite(instance, attribute, value) -> None: ...
def is_unit_length(instance, attribute, value, tol: float = 0.0001) -> None: ...
def value_is_validated(instance, attribute, value) -> None: ...
